# Generated by Django 5.2.3 on 2025-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanalysis',
            name='interview_status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
