# Generated by Django 5.2.3 on 2025-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='career_page_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
