# Generated by Django 5.2.3 on 2025-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_candidateanalysis_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanalysis',
            name='resume_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
