# Generated by Django 5.2.3 on 2025-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_candidateanalysis_resume_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.EmailField(blank=True, help_text='Email address of the sender.', max_length=255, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Date and time the application was received.', null=True)),
                ('experience', models.IntegerField(blank=True, help_text='Total years of professional experience.', null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, help_text='Email address found in the resume.', max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('resume_url', models.URLField(blank=True, help_text='URL to the downloaded resume file.', max_length=1000, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incoming Application',
                'verbose_name_plural': 'Incoming Applications',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
