# Generated by Django 5.2.3 on 2025-08-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-delivery_date', '-created_at'], 'verbose_name': 'Incoming Application', 'verbose_name_plural': 'Incoming Applications'},
        ),
    ]
