# Generated by Django 5.2.3 on 2025-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the job description.', max_length=255)),
                ('file', models.FileField(help_text='The uploaded job description file.', upload_to='job_descriptions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Description Document',
                'verbose_name_plural': 'Job Description Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
