# Generated by Django 5.2.3 on 2025-08-21 07:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_jobdescriptiondocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescriptiondocument',
            name='file',
            field=models.FileField(help_text='The uploaded job description file.', storage=django.core.files.storage.FileSystemStorage(location='media/job_descriptions'), upload_to=''),
        ),
    ]
