# Generated by Django 5.2.3 on 2025-08-28 15:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_alter_jobdescriptiondocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='benefits',
            field=models.TextField(blank=True, help_text='Company benefits and perks.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='department',
            field=models.CharField(blank=True, help_text='The department or team this role belongs to.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='education_experience',
            field=models.TextField(blank=True, help_text='Required education and work experience.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full-time', help_text='Type of employment (e.g., Full-time, Contract).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='job_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'Vice President')], default='mid', help_text='The experience level required for this position.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='location',
            field=models.CharField(blank=True, help_text='The primary work location (e.g., City, State, Remote).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='overview',
            field=models.TextField(blank=True, help_text='A brief overview of the role and its purpose.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='preferred_skills',
            field=models.TextField(blank=True, help_text='Desirable but not mandatory skills.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Mandatory skills and qualifications (e.g., Python, AWS, Agile).', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Key duties and responsibilities for this role.', null=True),
        ),
        migrations.AlterField(
            model_name='jobdescriptiondocument',
            name='file',
            field=models.FileField(blank=True, help_text='The uploaded job description file (optional if created via text).', null=True, storage=django.core.files.storage.FileSystemStorage(location='media/job_descriptions'), upload_to=''),
        ),
    ]
