# Generated by Django 5.2.3 on 2025-08-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_jobdescriptiondocument_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
