# Generated by Django 5.2.3 on 2025-08-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_application_job_role_application_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('Basic', 'Basic ATS Analysis'), ('Advance', 'Advanced ATS Analysis')], default='Basic', help_text='Type of resume analysis (Basic or Advanced).', max_length=10),
        ),
    ]
