# Generated by Django 5.2.3 on 2025-09-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr_app', '0010_candidateanalysis_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_host', models.CharField(help_text='SMTP server address (e.g., smtp.gmail.com)', max_length=255)),
                ('email_port', models.IntegerField(help_text='SMTP port number (e.g., 587)')),
                ('email_host_user', models.CharField(help_text='Email address for authentication', max_length=255)),
                ('email_host_password', models.CharField(help_text='Password or app-specific password for the email account', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use a TLS secure connection')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use a SSL secure connection')),
                ('email_from', models.CharField(blank=True, help_text="Sender's email address. If blank, uses the host user.", max_length=255)),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='jobdescriptiondocument',
            name='location',
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='city',
            field=models.CharField(blank=True, help_text='The city for the job location.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='company_name',
            field=models.CharField(blank=True, help_text='The name of the company posting the job.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='country',
            field=models.CharField(blank=True, help_text='The country for the job location.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='job_description',
            field=models.TextField(blank=True, help_text='The full, detailed description of the job role.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='salary_frequency',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='The frequency of the salary payment (e.g., Yearly, Hourly).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='salary_max',
            field=models.IntegerField(blank=True, help_text='The maximum salary for the position.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='The minimum salary for the position.', null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiondocument',
            name='state',
            field=models.CharField(blank=True, help_text='The state for the job location.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateanalysis',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('not_selected', 'Not Selected')], default='Pending', max_length=20, null=True),
        ),
    ]
