# Generated by Django 5.2.3 on 2025-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0011_emailconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, help_text='SMTP port number (e.g., 587)', null=True),
        ),
    ]
