"""
Django settings for Application_tracking_system project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dg*kx70rcfr1ve@n!5i2umhxg0#7g1z35u3-$ta_0%ih^x!0r&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "application-tracking-system-3haf.onrender.com"]
CSRF_TRUSTED_ORIGINS = [
    "application-tracking-system-3haf.onrender.com"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'hr_app',  # <-- This line is crucial!
    # ... other apps
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Application_tracking_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Application_tracking_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # <-- Tell Django where to find your static files
]
STATIC_ROOT = BASE_DIR / 'staticfiles' # For production deployment

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Custom Settings for API Keys (Hardcoded) ---
# IMPORTANT: Replace these with your actual keys.
# These are placeholder values.
BLANDAI_API_KEY = "org_a019efcc3f79c013e83b1836faff92322a7b66bb42da6ba8bcef569f4c02565e23db71fa9b631c9e6caa69" # <<< STATIC KEY
GOOGLE_API_KEY = "AIzaSyBQeaWpeQ3GFKC83Q5FT4V8d5SQ7VjhFB8" # <<< STATIC KEY
AIRTABLE_API_KEY = "patwhAkF1gv4aTK4V.ce7696f952c6176b9c601a76c3750363653c931c63a3965946666dd001b0a63b" # <<< STATIC KEY
AIRTABLE_BASE_ID = "app8swts0eepF8tdU" # <<< STATIC KEY

# Ensure a directory for uploaded resumes exists.
# This will be handled by Django's MEDIA_ROOT for user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
TIME_ZONE = 'UTC'

# Media files (user-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



RESUME_UPLOAD_ROOT = os.path.join(MEDIA_ROOT, 'resumes')
RESUME_UPLOAD_URL = MEDIA_URL + 'resumes/'

JOB_DESCRIPTION_UPLOAD_ROOT = os.path.join(MEDIA_ROOT, 'job_descriptions')
JOB_DESCRIPTION_UPLOAD_URL = MEDIA_URL + 'job_descriptions/'
# Outlook attachments will not be directly supported as explained
X_FRAME_OPTIONS = 'SAMEORIGIN'
